site_name: Initkoa Ecosystem Documentation
site_url: https://docs.initkoa.org
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue

plugins:
  - search
  - multirepo:
      cleanup: true
      repos:
        - section: SemantiK Architect
          import_url: https://github.com/Rejean-McCormick/SemantiK_Architect
        - section: Kristal Framework
          import_url: https://github.com/Rejean-McCormick/kristal-framework
        - section: kOA Digital Ecosystem
          import_url: https://github.com/Rejean-McCormick/kOA_Digital_Ecosystem
        - section: Konnaxion
          import_url: https://github.com/Rejean-McCormick/Konnaxion
        - section: Orgo
          import_url: https://github.com/Rejean-McCormick/Orgo
        - section: SenTient
          import_url: https://github.com/Rejean-McCormick/SenTient
