site_name: Initkoa Ecosystem Documentation
site_url: https://docs.initkoa.org
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue

plugins:
  - search
  - multirepo:
      cleanup: true
      repos:
        - section: SemantiK Architect
          import_url: https://github.com/Rejean-McCormick/SemantiK_Architect?branch=main
        - section: Kristal Framework
          import_url: https://github.com/Rejean-McCormick/kristal-framework?branch=main
        - section: kOA Digital Ecosystem
          import_url: https://github.com/Rejean-McCormick/kOA_Digital_Ecosystem?branch=main
        - section: Konnaxion
          import_url: https://github.com/Rejean-McCormick/Konnaxion?branch=main
        - section: Orgo
          # Orgo semble utiliser 'master' selon vos logs précédents, on le précise
          import_url: https://github.com/Rejean-McCormick/Orgo?branch=master
        - section: SenTient
          import_url: https://github.com/Rejean-McCormick/SenTient?branch=main